<?php
 $title = 'Edit admin';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url( 'zfcadmin/edit', array('action' => 'edit','id'=> $this->id,)));//#REPLACE-CHILD
 $form->prepare();
 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 $form_fields = $doneform->getNameFields($html = false, $actions = false);

 foreach ($form_fields as $ff){
    echo $this->formRow($form->get($ff));
 }
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();